# Generated by Django 4.2 on 2023-08-09 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll", models.CharField(max_length=10, null=True)),
                ("date", models.DateField()),
                ("cl", models.CharField(max_length=10)),
                ("present_status", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="MidtermResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test1", models.DecimalField(decimal_places=2, max_digits=5)),
                ("test2", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "total_mark",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=5, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now=True)),
                ("by", models.CharField(default="school", max_length=20, null=True)),
                ("message", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="StudentExtra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll", models.CharField(max_length=10)),
                ("mobile", models.CharField(max_length=40, null=True)),
                ("fee", models.PositiveIntegerField(null=True)),
                (
                    "cl",
                    models.CharField(
                        choices=[
                            ("one", "one"),
                            ("two", "two"),
                            ("three", "three"),
                            ("four", "four"),
                            ("five", "five"),
                            ("six", "six"),
                            ("seven", "seven"),
                            ("eight", "eight"),
                            ("nine", "nine"),
                            ("ten", "ten"),
                        ],
                        default="one",
                        max_length=10,
                    ),
                ),
                ("status", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeacherExtra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("salary", models.PositiveIntegerField()),
                ("joindate", models.DateField(auto_now_add=True)),
                ("mobile", models.CharField(max_length=40)),
                ("status", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "students",
                    models.ManyToManyField(
                        through="school.MidtermResult", to="school.studentextra"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="midtermresult",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="school.studentextra"
            ),
        ),
        migrations.AddField(
            model_name="midtermresult",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="school.subject"
            ),
        ),
        migrations.CreateModel(
            name="Marksheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marks", models.PositiveIntegerField()),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school.studentextra",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="school.subject"
                    ),
                ),
            ],
        ),
    ]
